### ISSUE TITLE
RippleWarpWallet doesn't work at all

### ISSUE THREAD

**Issue by doliverr** [termhn/ripplewarpwallet#1]
After entering a passphrase and clicking "Generate" will run the progress bar and "scrypt 524,288 of 524,288   pbkdf2 65,536 of 65,536", but nothing else happens. I am using the latest Firefox.

**Comment by fu5ha** [comment]
Hmm, interesting. I am getting the same behavior on latest firefox as well, though it's working perfectly on latest Chrome. I'll take a look and see what I can figure out; until, then if you wish to use the tool open it with Chrome 👍

**Comment by fu5ha** [comment]
Should be fixed by #2 and deployed to the site.  @doliverr
